### PR TITLE
Add intro screen

### PR DESCRIPTION
**Pull request by juliangruber**
New version of the original PR https://github.com/dat-land/dat-desktop/pull/498 by @aks-, with the branch available in this repository.

### CODE REVIEW

**Comment by juliangruber** [comment]
LGTM now :)

**Comment by aks-** [comment]
yeap, looks good and works good now

**Comment by juliangruber** [comment]
> I merged #507 into this branch (to test it out) and it shows the tutorial screen for a little until the persisted dat data is loaded. This can be partly mitigated by having a dedicated showIntro action rather than a hideIntro action. So my request would be to flip that the default-state is not intro but rather loading or startup with a dedicated action triggering the intro.

This can also be reversed: If we do that and the user opens the app when the intro needs to be shown, there will be a quick flash too.

I think this means we need to introduce not just `showIntro` but also `showTable`, so there's an anticipated state before either are visible.

**Comment by martinheidegger** [comment]
>> So my request would be to flip that the default-state is not intro but rather loading or startup with a dedicated action triggering the intro.

Well, the "loading" screen in my opinion should be a show/hide of the browser window:

https://github.com/electron/electron/blob/master/docs/api/browser-window.md#using-ready-to-show-event

**Comment by juliangruber** [comment]
Do you mean we shouldn't show the window at all before it has finished loading its internal state?

**Comment by martinheidegger** [comment]
@juliangruber exactly.

**Comment by juliangruber** [comment]
Let's fix the flashing in another PR, ok?

**Comment by juliangruber** [comment]
btw, I can't approve because I created this PR (using @aks-'s branch), so someone else will have to do so.

**Pull request merged**
